/* Database schema to keep the structure of entire database. */

CREATE TABLE animals(
ID INT NOT NULL AUTO_INCREMENT,
NAME CHAR,
DATE_OF_bIRTH DATE,
ESCAPE_ATTEMPTS INT,
NEUTERED BOOLEAN,
WEIGHT_KG DECIMAL,
PRIMARY KEY (ID)
);

// adding a new column species.
ALTER TABLE ANIMALS ADD COLUMN SPECIES CHAR(20);

